[package]
name = "pavi_query"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
arrow-array.workspace = true
parquet_reader = { path = "../parquet" }
pavi_runtime = { path = "../runtime" }

[dev-dependencies]
arrow-schema.workspace = true
parquet.workspace = true
tempfile = "3"
